replicaCount: 1

image:
  repository: alpine
  tag: "3.20"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: alpine.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

# Optional command / args to keep container alive
command: ["/bin/sh", "-c"]
args: ["while true; do sleep 3600; done"]

