apiVersion: v1
kind: Service
metadata:
  name: {{ include "alpine.fullname" . }}
  labels:
    {{- include "alpine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "alpine.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http

