---
# Source: alpine2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: helm-test-alpine2
  labels:
    helm.sh/chart: alpine2-0.2.1
    app.kubernetes.io/name: alpine2
    app.kubernetes.io/instance: helm-test
    app.kubernetes.io/version: "3.20"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: alpine2
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http

---
# Source: alpine2/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-test-alpine2
  labels:
    helm.sh/chart: alpine2-0.2.1
    app.kubernetes.io/name: alpine2
    app.kubernetes.io/instance: helm-test
    app.kubernetes.io/version: "3.20"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine2
  template:
    metadata:
      labels:
        app: alpine2
    spec:
      containers:
        - name: alpine2
          image: "alpine:3.20"
          imagePullPolicy: IfNotPresent
          stdin: true          # <-- tty + interactive support
          tty: true
          command: ["/bin/sh","-c"]
          args: ["while true; do sleep 3600; done"]
          resources:
            {}
