---
# Source: nats/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: helm-test-nats
  labels:
    helm.sh/chart: "nats-0.2.0"
    app.kubernetes.io/name: "nats"
    app.kubernetes.io/instance: "helm-test"
    app.kubernetes.io/version: "2.10"
    app.kubernetes.io/managed-by: "Helm"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "nats"
    app.kubernetes.io/instance: "helm-test"
  ports:
    - name: client
      port: 4222
      targetPort: 4222
      protocol: TCP

---
# Source: nats/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-test-nats
  labels:
    helm.sh/chart: "nats-0.2.0"
    app.kubernetes.io/name: "nats"
    app.kubernetes.io/instance: "helm-test"
    app.kubernetes.io/version: "2.10"
    app.kubernetes.io/managed-by: "Helm"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "nats"
      app.kubernetes.io/instance: "helm-test"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "nats"
        app.kubernetes.io/instance: "helm-test"
    spec:
      containers:
        - name: nats
          image: "nats:2.10-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: client
              containerPort: 4222
          resources:
            {}
