replicaCount: 2

image:
  repository: asdsadsa
  tag: "1.25-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: false   # prevents Helm from trying to create a ServiceAccount
  name: ""        # optional, leave empty if you don't need a custom SA

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: nginx.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
