apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alpine2.fullname" . }}
  labels:
    {{- include "alpine2.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "alpine2.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "alpine2.name" . }}
    spec:
      containers:
        - name: alpine2
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          stdin: true          # <-- tty + interactive support
          tty: true
          command: {{ toJson .Values.command }}
          args: {{ toJson .Values.args }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
